fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.2
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.1.3
    mysql: 
      repo: git://github.com/puppetlabs/puppetlabs-mysql.git
      ref: 2.3.1
    logrotate: git://github.com/rodjek/puppet-logrotate.git
    epel: git://github.com/stahnma/puppet-module-epel.git
    datacat: git://github.com/richardc/puppet-datacat.git
    zabbix: git://github.com/treydock/puppet-module-zabbix.git
  symlinks:
    zabbix_extras: "#{source_dir}"
