.travis.yml:
  allow_failures:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
spec/spec_helper.rb:
  requires:
    - 'lib/module_spec_helper'
